//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraduateAnswer
    {
        public int Score { get; set; }
        public long GraduateCode { get; set; }
        public long VariantTaskCode { get; set; }
        public long CriterionCode { get; set; }
    
        public virtual Criterion Criterion { get; set; }
        public virtual Graduate Graduate { get; set; }
        public virtual VariantSolution VariantSolution { get; set; }
    }
}
