//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Graduate()
        {
            this.GraduateAnswer = new HashSet<GraduateAnswer>();
        }
    
        public long GraduateCode { get; set; }
        public string Password { get; set; }
        public long CodeSubjectExpert { get; set; }
        public long VariantCode { get; set; }
        public Nullable<long> ExamCode { get; set; }
    
        public virtual ExpertSubject ExpertSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GraduateAnswer> GraduateAnswer { get; set; }
        public virtual Variant Variant { get; set; }
    }
}
