//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EducationSystemDB : DbContext
    {
        public EducationSystemDB()
            : base("name=EducationSystemDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Criterion> Criterion { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Examination> Examination { get; set; }
        public virtual DbSet<Expert> Expert { get; set; }
        public virtual DbSet<ExpertSubject> ExpertSubject { get; set; }
        public virtual DbSet<Graduate> Graduate { get; set; }
        public virtual DbSet<GraduateAnswer> GraduateAnswer { get; set; }
        public virtual DbSet<Solution> Solution { get; set; }
        public virtual DbSet<SolutionCriterionScore> SolutionCriterionScore { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<SubjectTask> SubjectTask { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<Variant> Variant { get; set; }
        public virtual DbSet<VariantSolution> VariantSolution { get; set; }
        public virtual DbSet<SolutionImages> SolutionImages { get; set; }
    }
}
