//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolutionCriterionScore
    {
        public long SolutionCriterionCode { get; set; }
        public string Comment { get; set; }
        public bool isValid { get; set; }
        public int PossibleScore { get; set; }
        public long SolutionCode { get; set; }
        public long CriterionCode { get; set; }
    
        public virtual Criterion Criterion { get; set; }
        public virtual Solution Solution { get; set; }
    }
}
