//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Solution = new HashSet<Solution>();
        }
    
        public long TaskCode { get; set; }
        public byte[] TaskImage { get; set; }
        [Required]
        [Range(1700, 3000, ErrorMessage = "Недопустимый год")]
        public int Year { get; set; }
        public byte[] CriterionFile { get; set; }
        public string CriterionFileName { get; set; }
        public int EventCode { get; set; }
        public int SubjectTaskCode { get; set; }
        public string Name { get; set; }
    
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solution> Solution { get; set; }
        public virtual SubjectTask SubjectTask { get; set; }
    }
}
