//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariantSolution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VariantSolution()
        {
            this.GraduateAnswer = new HashSet<GraduateAnswer>();
        }
    
        public long VariantTaskCode { get; set; }
        public long Number { get; set; }
        public long SolutionCode { get; set; }
        public long VariantCode { get; set; }
        public long ExamCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GraduateAnswer> GraduateAnswer { get; set; }
        public virtual Solution Solution { get; set; }
        public virtual Variant Variant { get; set; }
    }
}
